<?xml version="1.0" encoding="UTF-8"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="robot1">
  
  <xacro:include filename="$(find test)/urdf/plugin.gazebo" />


  <xacro:property name="chassis_x" value="0" />
  <xacro:property name="chassis_y" value="0" />
  <xacro:property name="chassis_z" value="0" />

  <xacro:property name="chassis_offset_z" value="${wheel_radius+chassis_size_z/2}" />

  <xacro:property name="chassis_size_x" value="0.5" />
  <xacro:property name="chassis_size_y" value="0.7" />
  <xacro:property name="chassis_size_z" value="0.1" />


  <xacro:property name="wheel_radius" value="0.15" />
  <xacro:property name="wheel_length" value="0.09" />
-
  <xacro:property name="joint_right_wheel_x" value="0.25" />
  <xacro:property name="joint_right_wheel_y" value="0.175" />
  <xacro:property name="joint_right_wheel_z" value="0.1" />

  <xacro:property name="right_wheel_offset" value="${wheel_length/2}" />

  <xacro:property name="lidar_x" value="0" />
  <xacro:property name="lidar_y" value="${-1*chassis_size_y/2}" />
  <xacro:property name="lidar_z" value="${wheel_radius+chassis_size_z}" />

  <xacro:property name="lidar_z_offset" value="0" />

  <xacro:property name="chassis_mass" value="0.7" />
  <xacro:property name="wheel_mass" value="0.1" />
  <xacro:property name="caster_mass" value="0.05" />



  <link name="base_footprint">
  </link>


  <!-- Chassis-->
<joint name="chassis_joint" type="fixed">
  <origin xyz="${chassis_x} ${chassis_y} ${chassis_z}" rpy="0.0 0.0 0.0"/>
  <parent link="base_footprint"/>
  <child link="chassis"/>
</joint>

  <link name="chassis">
    <inertial>
      <origin xyz="0.0 0.0 ${chassis_offset_z}" rpy="0.0 0.0 0.0"/>
      <mass value="${chassis_mass}"/>
      <inertia ixx="0.1" ixy="0.0" ixz="0.0" iyy="0.1" iyz="0.0" izz="0.1"/>
    </inertial>
    <visual name="">
      <origin xyz="0.0 0.0 ${chassis_offset_z}" rpy="0.0 0.0 0.0"/>
      <geometry>
        <box size="${chassis_size_x} ${chassis_size_y} ${chassis_size_z}"/>
      </geometry>
      <material name="">
        <color rgba="1.0 1.0 1.0 1.0"/>
        <texture filename=""/>
      </material>
    </visual>
    <collision>
      <origin xyz="0.0 0.0 ${chassis_offset_z}" rpy="0.0 0.0 0.0"/>
      <geometry>
        <box size="${chassis_size_x} ${chassis_size_y} ${chassis_size_z}"/>
      </geometry>
    </collision>
  </link>

   <!-- righ wheel-->

  <joint name="right_wheel_joint" type="continuous">
    <origin xyz="${joint_right_wheel_x} ${joint_right_wheel_y} ${wheel_radius}" rpy="0.0 1.5708 0.0"/>
    <parent link="chassis"/>
    <child link="right_wheel"/>
    <axis xyz="0 0.0 -1"/>
  </joint>

  <link name="right_wheel">
    <inertial>
      <origin xyz="0 0.0 ${right_wheel_offset}" rpy="0.0 0.0 0.0"/>
      <mass value="${wheel_mass}"/>
      <inertia ixx="0.1" ixy="0.0" ixz="0.0" iyy="0.1" iyz="0.0" izz="0.1"/>
    </inertial>
    <visual name="">
      <origin xyz="0 0.0 ${right_wheel_offset}" rpy="0.0 0.0 0.0"/>
      <geometry>
        <cylinder radius="${wheel_radius}" length="${wheel_length}"/> 
      </geometry>
      <material name="">
        <color rgba="0.2 1.0 0.2 1.0"/>
        <texture filename=""/>
      </material>
    </visual>
    <collision>
      <origin xyz="0 0.0 ${right_wheel_offset}" rpy="0.0 0.0 0.0"/>
      <geometry>
        <cylinder radius="${wheel_radius}" length="${wheel_length}"/> 
      </geometry>
    </collision>
  </link>



  <!-- left wheel-->
  <joint name="left_wheel_joint" type="continuous">
    <origin xyz="${-1*joint_right_wheel_x} ${joint_right_wheel_y} ${wheel_radius}" rpy="0.0 -1.5708 0.0"/>
    <parent link="chassis"/>
    <child link="left_wheel"/>
    <axis xyz="0 0.0 -1"/>
  </joint>
   
  <link name="left_wheel">
    <inertial>
      <origin xyz="0 0.0 ${right_wheel_offset}" rpy="0.0 0.0 0.0"/>
      <mass value="${wheel_mass}"/>
      <inertia ixx="0.1" ixy="0.0" ixz="0.0" iyy="0.1" iyz="0.0" izz="0.1"/>
    </inertial>
    <visual name="">
      <origin xyz="0 0.0 ${right_wheel_offset}" rpy="0.0 0.0 0.0"/>
      <geometry>
        <cylinder radius="${wheel_radius}" length="${wheel_length}"/> 
      </geometry>
      <material name="">
        <color rgba="0.2 1.0 0.2 1.0"/>
        <texture filename=""/>
      </material>
    </visual>
    <collision>
      <origin xyz="0 0.0 ${right_wheel_offset}" rpy="0.0 0.0 0.0"/>
      <geometry>
        <cylinder radius="${wheel_radius}" length="${wheel_length}"/> 
      </geometry>
    </collision>
  </link>

  <!-- caster wheel-->

  <joint name="caster_joint" type="continuous">
    <origin xyz="0 -0.25 ${wheel_radius/2}" rpy="0.0 -1.5708 0.0"/>
    <parent link="chassis"/>
    <child link="caster_link"/>
    <axis xyz="0.0 0.0 1.0"/>
  </joint>

  <link name="caster_link">
    <inertial>
        <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
        <mass value="${caster_mass}"/>
        <inertia ixx="0.1" ixy="0.0" ixz="0.0" iyy="0.1" iyz="0.0" izz="0.1"/>
    </inertial>
    <visual name="">
        <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
        <geometry>
            <cylinder radius="${wheel_radius/2}" length="${wheel_length}"/> 
        </geometry>
        <material name="">
            <color rgba="1.0 0.0 0.0 1.0"/>
            <texture filename=""/>
        </material>
    </visual>
    <collision>
        <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
        <geometry>
            <cylinder radius="${wheel_radius/2}" length="${wheel_length}"/> 
        </geometry>
    </collision>
  </link>

  <!-- lidar -->
  

  <joint name="lidar_joint" type="fixed">
    <origin xyz="${lidar_x} ${lidar_y} ${lidar_z}" rpy="0 0 -1.5708"/>
    <parent link="chassis"/>
    <child link="lidar"/>
  </joint>


  <link name="lidar">
    <collision>
      <origin xyz="0 0 ${lidar_z_offset}" rpy="0 0 0"/>
      <geometry>
        <mesh filename="package://test/meshes/hokuyo.dae"/>
      </geometry>
    </collision>

    <visual>
        <origin xyz="0 0 ${lidar_z_offset}" rpy="0 0 0"/>
        <geometry>
        <mesh filename="package://test/meshes/hokuyo.dae"/>
      </geometry>
    </visual>

    <inertial>
      <mass value="1e-5" />
      <origin xyz="0 0 ${lidar_z_offset}" rpy="0 0 0"/>
      <inertia ixx="1e-6" ixy="0" ixz="0" iyy="1e-6" iyz="0" izz="1e-6" />
    </inertial>
  </link>


 




</robot>